
let a = 10;
let b = 5;
 
let suma = a+b;
let resta = a-b;
let multiplicacion = a * b;
let division = a / b;
 
 
console.log("Resultado de la Suma: ", suma);
console.log("Resultado de la Resta: ", resta);
console.log("Resultado de la Multiplicacion: ", multiplicacion);
console.log("Resultado de la Division: ", division);
console.log("¿el resultado de la suma es igual a la resta? ", suma == resta);
console.log("el resultado de la multiplicacion es diferente al de division", multiplicacion =!division);
console.log ("¿ a es mayor que b ?", a > b);
console.log ("¿ a es menor o igual que b", a<=b)
    



